apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: mini-app
spec:
  containers:
    - name: oom
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["dd if=/dev/zero of=/dev/null bs=1M & tail -f /dev/null"]
      resources:
        limits:
          memory: "32Mi"
