apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: mini-app
spec:
  containers:
    - name: oom
      image: alpine
      command: ["/bin/sh", "-c"]
      # メモリを大量消費してOOMKillを再現
      args:
        - |
          echo "Allocating memory to trigger OOMKill..."
          # /dev/urandom から読み込んで変数に溜めてメモリを消費
          head -c 64M /dev/urandom > /tmp/data
          tail -f /dev/null
      resources:
        limits:
          memory: "32Mi"
  restartPolicy: Never
