apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-ingress
  namespace: mini-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: ws.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realtime-api
                port:
                  number: 8080
